---
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present

- name: Ensure pipx is installed
    pip:
    name: pipx
    executable: pip3

- name: Ensure global python packages for pipx are installed
    command: 
    cmd: python3 -m pipx install {{ item.name }}
    creates: ~pi/.local/bin/{{ item.name }}
  loop: global_python_packages

- name: Ensure ~pi/.local/bin is on the path (required for pipx installed tools)
    lineinfile:
    path: ~pi/.bashrc
    regexp: '^export PATH=~pi/\.local/bin'
    line: 'export PATH=~pi/.local/bin:$PATH'

- name: Ensure pi user's dotfiles are present in home folder
    copy:
    src: "{{ item }}"
    dest: ~pi/.{{ item.split("/")[-1] }}
    owner: pi
    group: pi
    mode: 0640
    with_fileglob:
    - "files/dotfiles/*"

- name: Ensure dotfiles are present for root user (for things like sudo vi ...)
    copy:
    src: "{{ item }}"
    dest: ~root/.{{ item.split("/")[-1] }}
    owner: root
    group: root
    mode: 0640
    with_fileglob:
    - "files/dotfiles/*"
    become: yes