---
- name: Include dotfiles configuration
  include_tasks: dotfiles.yml

- name: Include vim configuration
  include_tasks: vim.yml
  
- name: Ensure required OS packages are installed
  apt:
    name: python3-pip, python3-venv
    state: present
  become: yes

- name: Ensure pipx is installed
  pip:
    name: pipx
    executable: pip3

- name: Ensure global python packages for pipx are installed
  command:
    cmd: python3 -m pipx install {{ item }}
    creates: ~pi/.local/bin/{{ item }}
  with_items: "{{ global_python_packages }}"

- name: Ensure ~pi/.local/bin is on the path (required for pipx installed tools)
  lineinfile:
    path: ~pi/.bashrc
    regexp: '^export PATH=~pi/\.local/bin'
    line: 'export PATH=~pi/.local/bin:$PATH'

